apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc
  labels:
    app: odoo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-s3
