apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
     [options]
     ; This is the password that allows database operations:
     admin_passwd = @Fsone2020#IT

     addons_path = /mnt/extra-addons
     data_dir = /var/lib/odoo

     db_host = odoodb-do-user-22883732-0.i.db.ondigitalocean.com
     db_user = odoo_user2
     db_password = QWRtaW5QQHNzd
     db_port = 25060
     #list_db = True
     ;odoo_report_url = http://0.0.0.0:8069
     # proxy_mode = True

     limit_time_real = 5000
