apiVersion: v1
kind: Secret
metadata:
  namespace: csi-s3
  name: csi-s3-secret
stringData:
  accessKeyID: DO006HTF
  secretAccessKey: mZ4TiXAfjgVFXB4n
  endpoint: https://nyc3.digitaloceanspaces.com
